{-
  The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
  
  Let us list the factors of the first seven triangle numbers:
   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28
  We can see that 28 is the first triangle number to have over five divisors.

  What is the value of the first triangle number to have over five hundred divisors?
-}

(|>) = flip ($)

divisors :: Int -> [Int]
divisors k = divisors' 2 k
  where
    divisors' n k | n * n > k = [k]
                  | n * n == k = [n, k]
                  | k `mod` n == 0 = (n:(k `div` n):result)
                  | otherwise = result
      where result = divisors' (n + 1) k

result = zip [x * (x + 1) `div` 2 | x <- [1..]] [1..] 
         |> dropWhile (\(a,b) -> (<) (divisors a |> length) 500)
         |> head 
         |> fst